### ISSUE TITLE
Bug in key expansion

### ISSUE THREAD

**Issue by ZetaTwo** [mauricelambert/RC6Encryption#1]
Key expansion pseudo code: https://en.wikipedia.org/wiki/RC5#Key_expansion (RC5 and RC6 share key expansion)

Note the line: `do 3 * max(t, c) times:`

Compare with https://github.com/mauricelambert/RC6Encryption/blob/main/RC6Encryption.py#L235-L239

but it should be 

```
v = 3 * (
            self.key_blocks_number
            if self.key_blocks_number > self.round2_4
            else self.round2_4
        )
```

i.e. the multiplication by three should be on the outside of the expression.

**Comment by mauricelambert** [comment]
Thanks for opening this issue ! Sorry for the long response time.

I have check the algorithm and you have right, thanks for the information i will fix it now !

**Comment by mauricelambert** [comment]
Bug is fixed, thanks @ZetaTwo !
