### ISSUE TITLE
bug when generating L list

### ISSUE THREAD

**Issue by kuangjintao** [mauricelambert/RC6Encryption#2]
Extracted from wiki:
>  L is initially a c-length list of 0-valued w-length words
> for i = b-1 down to 0 do:
>    L[i/u] = (L[i/u] << 8) + K[i]

Which means:
```
L[3]= k[15]k[14]k[13]k[12]
L[2]= k[11]k[10]k[9]k[8]
L[1]= k[7]k[6]k[5]k[4]
L[0]= k[3]k[2]k[1]k[0]
```

One modification plan:
```
#block = f"{block}{bin(char)[2:]:0>8}"
block = f"{bin(char)[2:]:0>8}{block}"

#self.key_integer_reverse_blocks.reverse()
self.key_integer_reverse_blocks
```

**Comment by mauricelambert** [comment]
Thanks for opening this issue ! Can you send me the wiki link or identify the line in this algorithm: https://github.com/mauricelambert/RC6Encryption/blob/c2f748207a76af2adb0eb5824dad92a8a8a6605b/RC6Encryption.py#L44C1-L44C10 ?

```
Algorithm:

 - Key generation:
    S [0] = P32
    for i = 1 to 2r + 3 do
    {
        S [i] = S [i - 1] + Q32
    }
    A = B = i = j = 0
    v = 3 X max{c, 2r + 4}
    for s = 1 to v do
    {
        A = S [i] = (S [i] + A + B) <<< 3
        B = L [j] = (L [j] + A + B) <<< (A + B)
        i = (i + 1) mod (2r + 4)
        j = (j + 1) mod c
    }

 - Encryption:
    B = B + S[0]
    D = D + S[1]
    for i = 1 to r do
    {
        t = (B * (2B + 1)) <<< lg w
        u = (D * (2D + 1)) <<< lg w
        A = ((A ^ t) <<< u) + S[2i]
        C = ((C ^ u) <<< t) + S[2i + 1] 
        (A, B, C, D)  =  (B, C, D, A)
    }
    A = A + S[2r + 2]
    C = C + S[2r + 3]

 - Decryption:
    C = C - S[2r + 3]
    A = A - S[2r + 2]

    for i = r downto 1 do
    {
        (A, B, C, D) = (D, A, B, C)
        u = (D * (2D + 1)) <<< lg w
        t = (B * (2B + 1)) <<< lg w
        C = ((C - S[2i + 1]) >>> t) ^ u
        A = ((A - S[2i]) >>> u) ^ t
    }
    D = D - S[1]
    B = B - S[0]
```

I don't see a code like this: `for i = b-1 down to 0 do: L[i/u] = (L[i/u] << 8) + K[i]` in the algorithm.

**Comment by mauricelambert** [comment]
I'm trying to implement the change but i can't decrypt an encrypted string with the change suggestion.

I found the wiki: https://en.wikipedia.org/wiki/RC5 but it's for RC5. RC6 is derived from RC5 but i don't know if this element should be like RC5. If you have any additional information please let me know.

**Comment by kuangjintao** [comment]
Sorry, there was one line missing. Actually, three lines changes.
```
#unblock = partial(int.to_bytes, length=4, byteorder="big")
unblock = partial(int.to_bytes, length=4, byteorder="little")

#self.key_integer_reverse_blocks.reverse()
self.key_integer_reverse_blocks

#block = f"{block}{bin(char)[2:]:0>8}"
block = f"{bin(char)[2:]:0>8}{block}"
```

My encryption tests are as follows.
First, i do the encryption on an online website (https://www.lddgo.net/en/encrypt/rc6) , plaintext is "abcdefghijklmnop", key is "abcdefghijklmnop", and result in hex format is "bb05a4b6c46a24a8bf70e1e2c0a33e51" .

![rc6_online](https://github.com/mauricelambert/RC6Encryption/assets/106826683/84657682-de99-45a2-9111-7f5db93e84a2)

Second, i do the encryption with the RC6Encryption module, and result in hex format is "3d102dc8c58c8c11900b4b18d7876d82" .

![image](https://github.com/mauricelambert/RC6Encryption/assets/106826683/11f0805f-5f1f-4a36-ae78-3b25e8900c74)

Third, i change three line in the source file.

![changes](https://github.com/mauricelambert/RC6Encryption/assets/106826683/653a3af2-9511-4596-9fef-0a9c46998436)

Last, i do the encryption again and it works.

![after_changing](https://github.com/mauricelambert/RC6Encryption/assets/106826683/a7abed00-3347-4a91-b3a3-aecde8a8c004)

As for whether the element in RC6 should be like RC5, Wiki thinks so, and I also think so. 
> Note that the key expansion algorithm is practically identical to that of RC5. The only difference is that for RC6, more words are derived from the user-supplied key.

**Comment by mauricelambert** [comment]
Okay thanks for captures and details i will fix it !

**Comment by mauricelambert** [comment]
Thanks @kuangjintao for the reporting, the fix and examples and details !

The fix is push and a new unitest is added (using lddgo.net API).
